[package]
name = "cs492-concur-homework"
version = "0.1.0"
authors = ["Jeehoon Kang <jeehoon.kang@kaist.ac.kr>"]
edition = "2018"

[features]
check-loom = ["loom"]

[dependencies]
arr_macro = "0.1.3"
cfg-if = "1.0.0"
crossbeam-channel = "0.5.0"
crossbeam-epoch = "0.9.0"
crossbeam-utils = "0.8.0"
ctrlc = "3.1.7"
either = "1.6.1"
itertools = "0.9.0"
lazy_static = "1.4.0"
lock = { git = "https://github.com/kaist-cp/cs492-concur" }
lockfree = { git = "https://github.com/kaist-cp/cs492-concur" }
# lock = { path = "../cs492-concur/lock" }
# lockfree = { path = "../cs492-concur/lockfree" }
loom = { version = "0.3.6", optional = true }
rand = "0.7.3"
regex = "1.4.1"
static_assertions = "1.1.0"
